---
- name: Ports for x86_64
  include_vars: x86_64.yml
  when: ansible_architecture == "x86_64"
- name: Ports for aarch64
  include_vars: aarch64.yml
  when: ansible_architecture == "aarch64"
- name: Dependencies for distcc
  include_role:
    name: archlinux-devel
- name: Install distcc
  community.general.pacman:
    name: distcc
    state: present
    update_cache: yes
- name: Install cross toolchains and configure distccd
  include_tasks: server.yml
- name: Configure makepkg
  include_tasks: client.yml
...
