---
- name: Install x86_64 cross-compile toolchain
  community.general.pacman:
    name: distccd-x86_64
    state: present
    update_cache: yes
  when: ansible_architecture == "aarch64"
- name: Install aarch64 cross-compile toolchain
  community.general.pacman:
    name: distccd-alarm-armv8
    state: present
    update_cache: yes
  when: ansible_architecture == "x86_64"
- name: Allow private subnets
  ansible.builtin.lineinfile:
    path: /etc/conf.d/distccd
    regexp: '^DISTCC_ARGS='
    line: DISTCC_ARGS="-N 19 --allow-private --log-level error --log-file /tmp/distccd.log"
  notify: restart distccd
- name: Allow private subnets (x86_64 cross)
  ansible.builtin.lineinfile:
    path: /etc/conf.d/distccd-x86_64
    regexp: '^DISTCC_ARGS='
    line: DISTCC_ARGS="-N 19 --allow-private --log-level error --log-file /tmp/distccd-x86_64.log --port 3637"
  notify: restart distccd-x86_64
  when: ansible_architecture == "aarch64"
- name: Allow private subnets (armv8 cross)
  ansible.builtin.lineinfile:
    path: /etc/conf.d/distccd-armv8
    regexp: '^DISTCC_ARGS='
    line: DISTCC_ARGS="-N 19 --allow-private --log-level error --log-file /tmp/distccd-armv8.log --port 3636"
  notify: restart distccd-armv8
  when: ansible_architecture == "x86_64"
- name: Enable distccd
  ansible.builtin.systemd:
    name: distccd
    enabled: yes
- name: Enable distccd-x86_64
  ansible.builtin.systemd:
    name: distccd-x86_64
    enabled: yes
  when: ansible_architecture == "aarch64"
- name: Enable distccd-armv8
  ansible.builtin.systemd:
    name: distccd-armv8
    enabled: yes
  when: ansible_architecture == "x86_64"
...
